- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-cover:
            voting: false

